### PR TITLE
No link for last crumb.

### LINKED ISSUE #469: Breadcrumb for current album goes to #.
The href for the current album's breadcrumb is set to "#".  This takes you to the base path when clicked.  The old behavior was to not have the current album's breadcrumb be a link.

### PR DESCRIPTION
**Pull request by setnes**
A little ternary magic fixes #469.

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks!

I'll need to cherry-pick your commit as your branch seems to include all previous commits which haven't been merged yet.

**Comment by setnes** [comment]
Yeah...  I'm dealing with a little rebase nightmare again after trying to cleanup my master.

**Comment by oparoz** [comment]
It's really a pain when working on several large tasks at the same time as they may impact the same files. That's one reason I don't always submit one PR per change when dealing with smaller issues.

**Comment by setnes** [comment]
Yeah.  I'm still new to git.  I'm still trying to undo my mistake where I used my personal master branch for a pull request instead of keeping it identical to upstream.

**Comment by setnes** [comment]
There... that's better.

**Comment by oparoz** [comment]
Well done :)

**Comment by oparoz** [comment]
Doesn't work :( It kills the home icon, so looks like more thoughts will have to be given to that.

**Comment by setnes** [comment]
Hmm... you're right.  We might also have to look at the cssClass to see if it is the home link.

**Comment by oparoz** [comment]
> We might also have to look at the cssClass to see if it is the home link.

Sounds like the easiest solution

**Comment by setnes** [comment]
Try that.  It's not as elegant, but it doesn't destroy the home crumb... even when the home crumb is the last crumb.

**Comment by oparoz** [comment]
I think it won't work because :house: won't have the # needed to load the root folder any more.

**Comment by setnes** [comment]
It does have the #.  Look closer... or try it.  :)

**Comment by oparoz** [comment]
All good thanks :)

**Comment by setnes** [comment]
Cool.  :)

**Pull request merged**
