### PR TITLE
Fix height of public view

### PR DESCRIPTION
**Pull request by Henni**
As talked about in https://github.com/owncloud/core/pull/19611#issuecomment-146019871, this removes the scrollbar in the gallery view of the link share.

cc @oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
Currently OK when used with owncloud/core#19611. Waiting on the merge of that before completing work here.

**Comment by DeepDiver1975** [comment]
> Currently OK when used with owncloud/core#19611. Waiting on the merge of that before completing work here.

@oparoz its merged now - mind re-evaluation? THX

**Comment by oparoz** [comment]
I will, but I'd like to fix the footer in the same PR if possible. It currently doesn't look like on the Files side.

**Comment by Henni** [comment]
@oparoz I fixed the footer.

**Comment by oparoz** [comment]
OK. I'll test to see if it works in all situations:
- [x] Loading long infobox with short window should keep the infobox above the bottom border
- [x] Making the window taller should make the infox box grow
- [x] Load infobox with short window, close it, make window taller, re-open it. infobox should end above the bottom border
- [x] Load infobox with normal window, close it, make window shorter, re-open it. infobox should end above the bottom border

**Comment by oparoz** [comment]
Excellent work @Henni !

**Pull request merged**
