### PR TITLE
[stable9] Fix of issue #23066

### PR DESCRIPTION
**Pull request by butonic**
backport of https://github.com/owncloud/gallery/pull/652 to fix https://github.com/owncloud/core/issues/23066 in stable9

@oparoz @PVince81

### CODE REVIEW

**Comment by PVince81** [comment]
Makes sense :+1:

**Comment by oparoz** [comment]
The session tests are failing, so either they need to be altered or the fix is not as simple as casting to string.

**Comment by oparoz** [comment]
Ok, so it's simply a matter of fixing the tests and casting another ID: https://github.com/interfasys/galleryplus/pull/52/files

**Comment by PVince81** [comment]
Added extra cast in `checkPassword` and adjusted unit tests.

**Pull request merged**
