### PR TITLE
Required changes to the Preview ctor are effective since 10.0.9

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
hmm, a wild conflict appears ?!

**Comment by DeepDiver1975** [comment]
> hmm, a wild conflict appears ?!

resolved

**Comment by PVince81** [comment]
magic button, eh ? ;-)

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
