### PR TITLE
Listen for click actions on the upload stop button

### PR DESCRIPTION
**Pull request by oparoz**
Fixes: #630 
### Test plan

1. Upload a file
2. Click on the X next to the progress bar
### Tested on
- [x] Windows/Firefox
- [ ] Windows/Chrome
- [x] Ubuntu 14.04/Chrome
### Check list
- [x] Code is properly documented
- [x] Code is properly formatted
- [x] Commits have been squashed
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required
### Reviewers

@manishbisht @tahaalibra @viraj96 @imjalpreet @mbtamuli @rahulgoyal030 @shubhrajodiya @harshjv @kartik69 @senorsen

### CODE REVIEW

**Comment by harshjv** [comment]
This patch works as intended!

**Comment by virajparimi** [comment]
Yes, it works perfectly. Tested on Ubuntu 14.04/Chrome.

**Comment by viraj96** [comment]
But, I have one question though. What is supposed to happen if I am uploading multiple files at the same time and then cancel the upload. Now some files do get uploaded while some get cancelled depending on how fast I click the cancel button.

**Comment by manishbisht** [comment]
It's working checked on Ubuntu 14.04/Chrome and Ubuntu 14.04/Firefox.

**Comment by oparoz** [comment]
Thank you guys.

**Pull request merged**
