### PR TITLE
Close the share dialogue when performing another action, fixes #545

### LINKED ISSUE #545: Close the share dialogue when performing another action
### Steps to reproduce
1. Open the share dialogue
2. Click on an album

or
1. Open the share dialogue
2. Click on the info button
### Expected behaviour

The share dialogue should close
### Actual behaviour

The share dialogue stay open

### PR DESCRIPTION
**Pull request by virajparimi**
Fixes: #545 

Licence: AGPL
### Description

Close the share dialogue when performing "another action". Used hideDropDown function for share dialog.
### Features

Another actions include:
- Clicking on album.
- Clicking on image.
- Clicking on info button.
### Tested on
- [X] Ubuntu 14.04/Chrome
### Reviewers

@oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
Looks good to me. Would be good to get more testers in to see if they've noticed other areas where a dialogue is not hidden when performing another action.

**Comment by virajparimi** [comment]
Ok :) . @imjalpreet @tahaalibra @mbtamuli Please test this and tell if you noticed any other place where dialog is not hidden.

**Comment by mbtamuli** [comment]
Working fine. Did not notice any errors. 
Good work done. :+1:

**Comment by oparoz** [comment]
Thanks.

@viraj96 - Could you please squash your commits?

**Comment by virajparimi** [comment]
@oparoz Have squashed all commits. Please have a look. Thanks :)

**Comment by oparoz** [comment]
Thanks.

**Pull request merged**
