### PR TITLE
Keep error message in the session

### PR DESCRIPTION
**Pull request by oparoz**
Fix for https://github.com/owncloud/gallery/issues/296

@LukasReschke - Let me know if that meets your requirements.

The key points:
- https://github.com/owncloud/gallery/compare/keep-error-message-in-the-session?expand=1#diff-a8d3ad1f02ffca9503fa85aff518fc1dR143
- https://github.com/owncloud/gallery/compare/keep-error-message-in-the-session?expand=1#diff-e1b15e88afed87f9c3281c683fd9bab8R123
- https://github.com/owncloud/gallery/compare/keep-error-message-in-the-session?expand=1#diff-4b12e90075cad7aa65433b7c4bfc8063R110

### CODE REVIEW

**Comment by oparoz** [comment]
Rebased

**Comment by oparoz** [comment]
Rebased

**Comment by oparoz** [comment]
@karlitschek @DeepDiver1975 Needs to be reviewed today. Feel free to delegate to someone who can.

**Comment by karlitschek** [comment]
@LukasReschke @PVince81 @schiesbn @nickvergessen can you help with a review?

**Comment by LukasReschke** [comment]
Works :+1:

On a related note it might make sense to move this to the cookie for better UX but given that this only is used in the download controller this should be good as is anyways.

**Comment by oparoz** [comment]
Thanks for the review.
Just to be clear (for me). You mean that retrieving the info from the cookie is better than going: session->template->browser?

**Comment by LukasReschke** [comment]
> Just to be clear (for me). You mean that retrieving the info from the cookie is better than going: session->template->browser?

Yes. PHP sessions are blocking unless closed (which we do per default). So if a user clicks download and you set the `UseSession` annotation he can't do other things within the same session until the request is completed (other sessions will still work fine). Such as going to another picture and downloading this as well.

Though this is a pretty minor use case.

**Comment by oparoz** [comment]
Thanks.
I'd like to get rid of the customised error message for downloads. Session or cookies should not be used in a RESTful API anyway (and I want api controllers to mirror the standard one to keep things simple), but I need to make sure it still works with encryption. All the public controllers need `UseSession` in order to have access to the encrypted files.

**Comment by oparoz** [comment]
I've removed the session from the download method and it still works with encryption.

Tests fail because `core` master is broken. They all pass locally, when not running in single user mode.

**Pull request merged**
