### PR TITLE
update toggle icon, remove outdated download icon, ref #51

### PR DESCRIPTION
**Pull request by jancborchardt**
Fixing https://github.com/owncloud/gallery/issues/51 together with https://github.com/owncloud/core/pull/22654

Please review @owncloud/designers @oparoz

@oparoz I removed the outdated download icon because view-download from core should be used. I didn’t add the toggle icon to core since we should still think about a better solution here than a button. Anyway, different discussion. :)
### Tested on
- [x] Windows/Firefox
- [x] Windows/Chrome
- [ ] Android 4.x/Chrome
- [x] iOS9/Safari
- [x] BlackBerry10/Browser 
### Check list
- [x] Code is properly documented
- [ ] Commits have been squashed
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required
### Reviewers

@MorrisJobke @setnes @demattin

### CODE REVIEW

**Comment by MorrisJobke** [comment]
:+1:

**Comment by oparoz** [comment]
Thanks for the fixes :)

slideshow.css needs to be updated to use the icon from core since it doesn't exist in Gallery any more.

**Comment by jancborchardt** [comment]
@oparoz for some reason the download icon does not show up for me in the detail view. How can I invoke it?

Because otherwise I would just remove the line `background-image: url("../img/download.svg");`

**Comment by oparoz** [comment]
@jancborchardt - Maybe you're not on the right branch in `core` since it needs to be available there?

**Comment by jancborchardt** [comment]
@oparoz I’m on the icon-fixes branch in both core and gallery. This is what I see:
capture du 2016-02-25 21-54-27
The download icon is neither next to the file name nor at the top. What am I doing wrong? :D

**Comment by oparoz** [comment]
Must be a cache, issue, I've just tried with `core` master since it now has the new icon and disabling `background-image` in `slideshow.css` does the trick.

**Comment by jancborchardt** [comment]
@oparoz updated the CSS. Still can’t see the icons :\

Actually, are those full blocks of CSS not outdated now, maybe except setting the height / width (although that should be 32px, no?)? Because the size of the image is the same now as the close / previous / play buttons, and should be displayed the same.
Sorry I can’t fix it myself … no idea why that doesn’t work.

**Comment by oparoz** [comment]
> updated the CSS. Still can’t see the icons :\

Hmmm... That's going to be a problem if it doesn't work for everybody...
Anything in the network tab? What does the CSS for the icon look like? There should be a background-image entry.
Maybe you're using a different theme?

> Actually, are those full blocks of CSS not outdated now, maybe except setting the height / width (although that should be 32px, no?)? Because the size of the image is the same now as the close / previous / play buttons, and should be displayed the same.

Yes, I played with that yesterday and they should be 32px I can fix that in this PR. I was also thinking of moving the play button next to the others for consistency, as a first step towards having some sort of menu which can shrink to 3dots.

**Comment by oparoz** [comment]
@jancborchardt - You need to launch the slideshow from Gallery. There is no download icon on the Files side since there is already one on every row.

**Comment by jancborchardt** [comment]
@oparoz I also launched it from the gallery side, especially in the screenshot I took above. Besides, the actions should always be there in the details view, no matter if coming from the Files or Gallery view.

That’s the point – sure they are in the list, but if I see a picture I want to share or download, I want to do it right then and there. Not need to go back and find it in the list and then share it. ;)

**Comment by oparoz** [comment]
> ..., especially in the screenshot I took above

I doubt that. The URL in the screenshot clearly shows a public Files page ;)

> That’s the point – sure they are in the list, but if I see a picture I want to share or download, I want to do it right then and there. Not need to go back and find it in the list and then share it. ;)

Share, yes, especially on social networks, but for downloads, you need to build the case in a feature request because it's not that straight forward. I find it much more useful to be able to pick a few pictures and download them in one go than to have to download every single one of them.

**Comment by jancborchardt** [comment]
Merging as we can fix anything else going forward.

**Pull request merged**
