### PR TITLE
Do not allow empty urls to be submitted in "add to your owncloud"

### PR DESCRIPTION
**Pull request by virajparimi**
Fixes: #556 

Licence: AGPL
### Description

Fixed the error that came when no URL was entered. Added a new public method to galleryview.js file.
### Tested on
- [x] Ubuntu 14.04 LTS/Chrome
### Reviewers

 @oparoz

### CODE REVIEW

**Comment by virajparimi** [comment]
@oparoz  Please have a look at the fix.

**Comment by oparoz** [comment]
Thanks for the PR. There are a few issues with it.
1. A PR has to be based off `master`. This one seems to be a fork of your last PR
2. You have to make a choice in the license field in the PR. If you haven't signed the contributor agreement and you're OK with releasing your work under the MIT license, pick MIT
3. There is no need to include public.js at this stage. All the functions related to the public side are in gallery.js. Maybe this can be split later so that some code is only loaded on the public side, but it's best to move everything at the same time.

**Comment by virajparimi** [comment]
OK 
So, I just need to remove public.js and and copy the same code to gallery.js. And where do I find the contributor agreement?

**Comment by oparoz** [comment]
https://owncloud.org/contribute/agreement/

**Comment by virajparimi** [comment]
@oparoz Have a look at the new one. Have removed the  public.js file.

**Comment by oparoz** [comment]
Your fix doesn't work properly.
You've created a new method which is never called. 
I was wrong before, since this only makes changes to the view, it's best to move it to galleryview, but make sure it's called during the initialisation of the view.

**Comment by virajparimi** [comment]
@oparoz I have fixed the issue which was unresolved. Please have a look.

**Comment by oparoz** [comment]
Thanks. If you leave it where it is in `_init`, then this will be called every time the view is initialised.
The line below your change mentions that there is a special method for initialising buttons only once.
I would add the call there.

Makes sense?

**Comment by virajparimi** [comment]
@oparoz Have made the change you suggested.

**Comment by oparoz** [comment]
A couple of points:
1. We use camelCase to name methods
2. private methods start with an underscore
3. methods should be documented
4. if possible, try to find a meaningful name for the method without making it too long. That makes it easier to understand what it does.

**Comment by virajparimi** [comment]
@oparoz Have a look at  the update. I have made the method public. Thanks!

**Comment by oparoz** [comment]
Why public? It's not being called anywhere but in galleryview

**Comment by virajparimi** [comment]
@oparoz  I initially did make it private but later thought  that maybe later it will be called in some other files so I ended up  making it public. Well now I have updated it. Have a look. Thanks.

**Comment by oparoz** [comment]
I've just tested the solution and there is one more thing missing. The CSS needs to be adjusted to make it work like on the Files side. Without it, we don't really see when the button is enabled/disabled.

**Comment by virajparimi** [comment]
@oparoz I have fixed that issue as well and even squashed all commits. Please have a look. Thanks!

**Comment by oparoz** [comment]
Looks good. I will test as ASAP.

@tahaalibra you can test this and see if it works like on the Files side

**Comment by tahaalibra** [comment]
:+1:  works well
tested on both files and gallery

**Comment by oparoz** [comment]
Thanks. I've tested as well and it works as expected. Thank you @viraj96

**Pull request merged**
