### PR TITLE
Make share.js work with new OCS Share API

### LINKED ISSUE #508: Adjust sharing for 9.0
With https://github.com/owncloud/core/pull/22231 we drop some of the old sharing ajax calls which are still being used in the gallery.

The code has to be migrated to OCS calls.

@rullzer maybe you can help out here to get this up and running again - THX

### PR DESCRIPTION
**Pull request by oparoz**
Fixes: #508, #538 
### Description

This fixes the share dialogue so that people can share from Gallery again
### Features
- Gets the job done
- Does not use the Sharee API
- Still a mess of intertwined JS and CSS
- Replaced tipsy with tooltip
- Does not include any new features (like public uploading or link emailing)
### Caveats
- Performs 2 sync ajax calls on the main thread. The fix would be to create an empty dropdown while we wait for the result of the async requests
### Tests

Feel free to add more. Is there a standardised list? Or some acceptance tests which could be tweaked to run from Gallery instead of Files?

UserA shares with UserB who shares with UserC
#### UserA
- [x] UserA can share with a UserB
- [x] UserA can unshare with UserB
- [x] UserA can change share permissions and UserB gets the new permissions
- [x] UserA can create/remove a link
- [x] UserA can add/remove a password
- [x] UserA can add/remove an expiration date
#### UserB
- [x] UserB can see the share received from UserA
- [x] UserB can share with UserC
- [x] UserB can unshare with UserC
- [x] UserB can change share permissions and UserC gets the new permissions
- [x] UserB can create/remove a link
- [x] UserB can add/remove a password
- [x] UserB  can add/remove an expiration date
#### UserC
- [x] UserC can see the share received from UserA
#### Error testing
- [x] 403 errors are shown in an error message 
### Tested on
- [x] Windows/Firefox
- [x] Windows/Chrome
### TODO
- [x] Determine which behaviour is correct in https://github.com/owncloud/core/issues/22702 and act accordingly
- [ ] Hide the share dialogue when opening an album
### Check list
- [x] Code is properly documented. Good enough, better then before
- [x] Commits have been squashed
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required
### Reviewers

@rullzer @MorrisJobke @PVince81 @jospoortvliet @jancborchardt @setnes @demattin

### CODE REVIEW

**Comment by oparoz** [comment]
As UserC, reshares from UserB, owned by UserA are shown as shared by UserA. This seems strange to me, but I don't know which behaviour is correct. See https://github.com/owncloud/core/issues/22702

**Comment by rullzer** [comment]
Awesome work so far @oparoz clicked around a bit and so far my installation did not blow up!

**Comment by davitol** [comment]
Tested in Firefox for MacOSX and I didn't work for me. Applying the patch the available users to share don't appear :-1: @oparoz If you want to see my test enviroment feel free to ping me on the irc

**Comment by rullzer** [comment]
@davitol please have another look

**Comment by PVince81** [comment]
Seems to work fine.
1. Create two folders "test-files" and "test-gallery"
2. Upload a bunch of pictures into them
3. For both "files" and "gallery" apps as $APP:
   1. "admin" opens $APP
   2. "admin" shares a folder "test-$APP" with "user1"
   3. "user1" opens $APP
   4. "user1" reshares "test-$APP" with "user2"
   5. "user2" sees the folder "test-$APP"
4. as "admin", check the list of sharees for "test-files" and "test-gallery" in the files app
5. as "admin", check the list of sharees for "test-files" and "test-gallery" in the gallery app

In both cases, "user1" and "user2" appeared in the list of sharees. This looks correct.

@davitol does it work for you now ? If not, please provide detailed steps as I did. Make sure to be precise where you created the share and where you looked whether the share existed. (files app or gallery app).

:+1:

**Comment by davitol** [comment]
:+1: WFM now

**Comment by rullzer** [comment]
@oparoz I suggest to follow up on your open checkboxes in different PR's. Now at least the basic sharing works again.

**Pull request merged**
