### PR TITLE
Fix for string id

### PR DESCRIPTION
**Pull request by PVince81**
Gallery part for https://github.com/owncloud/core/issues/23066
- stable9.1: https://github.com/owncloud/gallery/pull/690
- stable9: https://github.com/owncloud/gallery/pull/682

@butonic @oparoz 

will have a look at the unit tests that were mentionned to fail

### CODE REVIEW

**Comment by oparoz** [comment]
Is this really necessary for 9.1+ ? I thought it only was a problem on 9.

**Comment by PVince81** [comment]
I don't have an env to reproduce the original issue so better be sure.
I'm not aware of any code in 9.1 that would make this fix unnecessary.

**Comment by oparoz** [comment]
OK, thanks. I never had any issue on 9.1, but as you said, it doesn't hurt to keep this change in.

**Comment by PVince81** [comment]
I'll prepare the backports.
The one from @butonic is incomplete, will finish it.

**Pull request merged**
