### PR TITLE
Make progressbar clickable

### PR DESCRIPTION
**Pull request by oparoz**
Fix for "_Pause button is sometimes not clickable_" #407

@Henni

### CODE REVIEW

**Comment by Henni** [comment]
Please add `cursor:pointer` to the progress-bar. Otherwise the cursor "flickers".

**Comment by oparoz** [comment]
It didn't flicker here, so I didn't bother, but I've pushed the fix.

**Comment by Henni** [comment]
:+1:

**Comment by oparoz** [comment]
Thanks for the review :)

**Comment by oparoz** [comment]
Fix has been added to an all in one branch https://github.com/owncloud/gallery/pull/421

**Pull request closed without merging**
