### PR TITLE
Do not allow access to write-only shares

### PR DESCRIPTION
**Pull request by LukasReschke**
Adds checks as required for https://github.com/nextcloud/server/pull/19

### CODE REVIEW

**Comment by LukasReschke** [comment]
@oparoz As discussed.

**Comment by LukasReschke** [comment]
@oparoz I don't quite understand why the tests are failing here. Could you help me on that? That would be awesome 🚀

**Comment by oparoz** [comment]
Because core is broken: https://github.com/owncloud/gallery/issues/663, so until either core is fixed or a workaround is implemented, all tests will fail on master.

The backport is not affected, there is only 1 failed test which you can probably easily fix.

**Comment by oparoz** [comment]
Closed in favour of #672

**Pull request closed without merging**
