### PR TITLE
Import legacy share dialog code

### PR DESCRIPTION
**Pull request by PVince81**
This is to make the share dropdown work again
- [x] TODO: fix checkboxes

Let's wait for the checkboxes to be fixed in https://github.com/owncloud/calendar/pull/940 then grab the share.js file from there again.

@oparoz @blizzz

### CODE REVIEW

**Comment by karlitschek** [comment]
thanks for the fix aka workaround :+1:

**Comment by PVince81** [comment]
I have updated the code, but there seem to be additional issues with the checkboxes @Henni 
checkbox-issue-gallery-share

This wasn't visible in the calendar app because there was no link share.
Best would be to search for all occurences of "checkbox" in that file and make the change.
Hint: there are other hidden checkboxes that only appear when setting options in the "Admin" page

**Comment by oparoz** [comment]
Thank you very much for this @PVince81 :)

**Comment by PVince81** [comment]
@Henni do you intend to fix the checkboxes here too ?
Another alternative is reverting them back to the old style, basically grabbing share.js before your changes.

**Comment by Henni** [comment]
I'll take a look at this.
Does this issue still exist or are the old checkboxes properly displayed?

**Comment by oparoz** [comment]
> Does this issue still exist or are the old checkboxes properly displayed?

Has there been a change merged in master recently to fix this?

**Comment by Henni** [comment]
@oparoz https://github.com/owncloud/core/pull/19329

**Comment by oparoz** [comment]
Thanks @Henni 

So, the checkboxes look like the old ones and I'm guessing we need to fix the CSS in another PR by adding the new class to the elements and possibly modify them?

Apart from that, it all seems to work, apart from mail notifications, but which never worked. Good job @PVince81.

**Comment by PVince81** [comment]
Ok then I guess I'll grab the old share.js version which didn't have half of the checkboxes moved to the new style. So in the end the legacy share dropdown will only have old checkboxes.

**Comment by PVince81** [comment]
@oparoz I have replaced the code in this PR with the older share.js, the one without half the checkboxes changed. I suggest to merge this first.

If you want the new checkbox styles this can be done in a separate PR.

**Comment by oparoz** [comment]
Is it OK if I move that code to the vendor folder? It's like a library to me.

**Comment by PVince81** [comment]
As you like, feel free to push here

**Comment by oparoz** [comment]
OK. Any idea why "sending an email" never shows up when using that dialogue? Is it working in the other apps?

**Comment by oparoz** [comment]
@henni, seems like there is a bug with the fallback

fallback_not_working

**Comment by oparoz** [comment]
Rebased

**Comment by icewind1991** [comment]
Fixed password protect checkbox



With password protect enforced:

**Comment by oparoz** [comment]
Report from @Dianafg76

| Test case | Browser | Result |
| --- | --- | --- |
| Share from the Gallery a folder | Firefox, Chrome, Safary | OK |
| Share with password | Firefox, Chrome, Safary | OK |
| Share with expiration time | Firefox, Chrome, Safary | OK |
| Share with password and expiration time | Firefox, Chrome, Safary | OK |
| Force from admin to share with password | Firefox, Chrome | OK |
| Force from admin to share with password | Safary | NOK (https://github.com/owncloud/gallery/issues/399) |

**Pull request merged**
