### PR TITLE
replace logo-wide on share page with better icon + text, as in core

### PR DESCRIPTION
**Pull request by jancborchardt**
According to https://github.com/owncloud/core/pull/16517 – please review @owncloud/designers @oparoz @icewind1991 @DeepDiver1975

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by oparoz** [comment]
Doesn't work. completely breaks the header on 8.0. The updated core CSS would need to be added to the app's CSS or the PR should be moved to sit on top of dev if the original change in core is not intended to be backported to stable8.

**Comment by MorrisJobke** [comment]
> sit on top of dev if the original change in core is not intended to be backported to stable8.

The change is only intended for 8.1. @oparoz Can you cherry pick this into dev? @jancborchardt is on vacation this week. Thanks

**Comment by oparoz** [comment]
OK, will do

**Comment by oparoz** [comment]
It's merged

**Comment by oparoz** [comment]
@jancborchardt - If you've submitted this patch to a few apps, you may want to make a modification so that they don't lose their compliance status. Your patch introduces a private API in the template.

Here is how I fixed it:
https://github.com/owncloud/galleryplus/commit/84141592e65f868955e5472dabc773571c5a34e1

**Comment by jancborchardt** [comment]
@oparoz right, thanks for the note! @schiesbn @DeepDiver1975 can you comment on that? ^ Is it correct and should we do it like that?

**Pull request closed without merging**
