### PR TITLE
improve iOS scrolling as per @fuhaoshih's pull request #285

### PR DESCRIPTION
**Pull request by jancborchardt**
PR superseding https://github.com/owncloud/gallery/pull/285

(Couldn’t cherry-pick because of the conflicts.) Please review @oparoz @owncloud/designers @fuhaoshih

### CODE REVIEW

**Comment by jancborchardt** [comment]
@mmattel please review too.

**Comment by oparoz** [comment]
It's been approved in the other PR already, but I'm curious. Has anybody tested this on other browsers to see if it has any side effects? It shouldn't, but I'd rather be sure.

**Comment by mmattel** [comment]
I have checked this, but it seems that the css parameter does not get triggered, maybe positioned on the wrong place, but I am not a css expert. 

I have tested on my iPad following page where you can test this with and without and there it works:
https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

I have used private browsing mode and also cleared the iPad Safari cache ect. but without success.

It also seems according to google search that an overflow parameter hast to be set too, but this also did not change anything in my test...

```
overflow-y: scroll;                 /* has to be scroll, not auto */
-webkit-overflow-scrolling: touch;
```

I would appreciate if that would work :smile:

**Comment by oparoz** [comment]
It breaks non-Safari browsers, so :-1: 
https://github.com/owncloud/core/issues/19334

I'm sure there are ways to make it work without breaking stuff, but apparently, it's going to take more effort than that one line.

**Comment by jancborchardt** [comment]
Closing then, thanks for the catch @oparoz

**Pull request closed without merging**
