### PR TITLE
Protect users from gallery.cnf

### LINKED ISSUE #295: gallery.cnf leads to XSS
``` yaml

---
# Gallery configuration file
information:
  description: This <script>alert(1)</script>is an **album description** which is only shown if there is no `description_link`
  copyright: Copyright 2003-2015 [interfaSys sàrl](javascript:alert(1\)), Switzerland
  inherit: yes
sorting:
  type: date
  order: des
  inherit: yes
features:
  external_shares: yes
  native_svg: yes
```

Personally I'd advise to remove this info stuff as it can easily lead to further security issues while offering few advantages.

cc @jancborchardt

### PR DESCRIPTION
**Pull request by oparoz**
Fixes #295 
- Enabled the sanitizing option of marked
- Added DOMPurify
- Added custom rules to DOMPurify

@LukasReschke

### CODE REVIEW

**Comment by oparoz** [comment]
So, @LukasReschke. Is this working for you?
I tested with your example and a few others, but you probably have better tools :)

**Comment by oparoz** [comment]
Rebased

**Comment by oparoz** [comment]
@karlitschek @DeepDiver1975 Needs to be reviewed today. Feel free to delegate to someone who can.

**Comment by karlitschek** [comment]
@LukasReschke @PVince81 @schiesbn can you help to review?

**Comment by LukasReschke** [comment]
:-1: - the sanitize function of marked [is not secure enough](https://github.com/chjj/marked/pulls?utf8=%E2%9C%93&q=is%3Aopen+sanitize+is%3Apr+) please use commonmark.js as advised at https://github.com/owncloud/gallery/issues/295#issuecomment-137421791

Try something like: 

```
---
# Gallery configuration file
information:
  description: This <script>alert(1)</script>is an **album description** which is only shown if there is no `description_link`
  copyright: Copyright 2003-2015 [URL](javascript&#58document;alert&#40;1&#41;)
  inherit: yes
sorting:
  type: date
  order: des
  inherit: yes
features:
  external_shares: yes
  native_svg: yes
```

Note that DOMPurify does just nothing in IE 8 :-)

**Comment by LukasReschke** [comment]
Or even more secure remove the feature :speak_no_evil: :see_no_evil: :hear_no_evil: _runs away and hides_ ;-)

**Comment by oparoz** [comment]
The example you gave is neutralized. The first part is converted to text and the second one is completely removed.

In the link you gave, to the list of PRs, there is only one which is relevant, but which is caught by DOMpurify:
https://github.com/chjj/marked/pull/592

I'll check commonmark to see if there are no rendering issues. There is also mardown-it, which also cares about security. They've all made good progress recently regarding speed.

Looking at DOMPurify's doc, I can confirm that I need to remove Gallery configuration support for IE8-9. Not a big deal.

**Comment by LukasReschke** [comment]
No. DOMPurify is not a proper solution. The Markdown parser on it's own should be secure as well. It's like relying on an AV to make your PC more secure. It might be nice to have but it is in no way a proper defense in depth.

> I'll check commonmark to see if there are no rendering issues. 

:+1:

> There is also markdown-it, which also cares about security. They've all made good progress recently regarding speed.

_googles for markdown-it_

**Comment by oparoz** [comment]
OK!

**Comment by oparoz** [comment]
Done. No problem with speed with the type of content being displayed.

@LukasReschke Let me know if that now meets your requirements.

**Comment by LukasReschke** [comment]
Can we use DOMPurity 0.6.7 (or directly 0.7.0) as it fixes a bypass?

Ref https://github.com/cure53/DOMPurify/releases/tag/0.6.7

**Comment by oparoz** [comment]
Of course. Can me merge this and I then update all bower and composer packages?

**Comment by LukasReschke** [comment]
Yup. Let's do it that way.

**Pull request merged**
