### PR TITLE
Big area for "next" and "prev" buttons. useful for mobile devices.

### PR DESCRIPTION
**Pull request by 0xb0ba**

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks for your contribution. Have you checked to see if zooming via the scroll-wheel is still working on the desktop? That's the problem we faced with the last PR which was submitted.

**Comment by 0xb0ba** [comment]
no, does not work when the cursor is over ".prev" or ".next" or ".menu" or ".name". in this case the prev and next of width 25%

**Comment by oparoz** [comment]
OK, so I've tested this. It's frustrating, because on Chrome, zooming works fine from anywhere, but not on Firefox.

Even though it's only 25% of the horizontal space, I'm still not convinced it won't confuse users. On the one hand, the cursor changes, so it should be obvious that that area can be clicked, but it's a bit annoying to have to keep the cursor in the centre of the image.

@jancborchardt @demattin @setnes Any thoughts for or against this change?

**Comment by setnes** [comment]
I absolutely love this change.  It's a simple way to make things a lot easier on a mobile device.

I agree with @oparoz, about the Chrome vs Firefox zooming though.  This needs to be figured out if at all possible... or maybe balanced with a smaller percentage.

**Comment by 0xb0ba** [comment]
OK, let's find a solution for Firefox. I think the problem is "onwheel" and "onmousewheel"

**Comment by oparoz** [comment]
Probably, but just like for pinch-to-zoom which only works on iOS, it may be difficult to fix since the handlers are in Bigshot...

**Comment by jancborchardt** [comment]
Does clicking the image itself also work for advancing the image? That would be really cool as addition. :)

**Comment by oparoz** [comment]
> Does clicking the image itself also work for advancing the image? That would be really cool as addition. :)

That might make it unnecessary to make the buttons larger, but it might not be possible to do due to interferences with Bigshot...

**Comment by 0xb0ba** [comment]
> to make the buttons larger

25%+75%

**Comment by oparoz** [comment]
> 25%+75%

That's what use in the other PR, but it blocked the zooming.

**Comment by setnes** [comment]
I tried 15% instead of 25%.  This still gave a much better mobile experience without getting in the way (as much) with zooming with a mouse.  It seems like a better balance given the circumstances.

**Comment by oparoz** [comment]
So @jancborchardt , should we go with 15% even if it blocks scrolling on Firefox or wait for a better solution?

**Comment by 0xb0ba** [comment]
@oparoz last commit work in firefox

**Comment by oparoz** [comment]
Ah, I missed that :) Thanks. I'll try asap. That means that we would be able to go to 25-75 is we wanted to.

**Comment by PVince81** [comment]
@oparoz did you get a chance to have a look ?

**Comment by oparoz** [comment]
Thank you for your contribution @0xb0ba. That's really useful.

Merged as-is. A separate PR can be open if the invisible buttons need to be of different dimensions.

**Comment by oparoz** [comment]
This needs to be backported to 8.2.2

**Comment by jancborchardt** [comment]
@0xb0ba @oparoz you can do a backport via git cherry-pick on the commit to stable8.2 :)

**Pull request merged**
