### PR TITLE
Do not show spinner when home is current and home clicked

### PR DESCRIPTION
**Pull request by VicDeo**
Ref https://github.com/owncloud/enterprise/issues/2127
1. Open gallery
2. Click 'home' icon
3. See never ending spinner

### CODE REVIEW

**Comment by tomneedham** [comment]
Resolves the issue 👍 Now will look at the builds

**Comment by tomneedham** [comment]
Looks like a dependency collision with core `Symfony\Component\Yaml`

**Comment by PVince81** [comment]
All Travis is red.

@VicDeo please resolve separately and have this PR only include "the fix".

We'll need a new release of gallery app but likely will want to have CI sorted out by then, cc @patrickjahns

**Comment by VicDeo** [comment]
@PVince81 it's red for over a year https://github.com/owncloud/gallery/commits/master
I already spent  ~ 2 days in total resolving Travis issues for these 3 lines of js so estimates on fixing Travis are unclear.

**Comment by patrickjahns** [comment]
The other option would be to move gallery to drone - but we would most likely need to deal with js issues there as well

@PVince81 
release ticket is here: https://github.com/owncloud/gallery/issues/761 - please fill in specifics (if available)

**Comment by VicDeo** [comment]
it's not a js issue. Failures are  related to composer deps.

**Comment by PVince81** [comment]
Ah ok, so there are JS tests, good to know.

How long would it take to sort out the failures / setup then ?

**Comment by VicDeo** [comment]
@PVince81 For me it's a big piece of PITA but I think it's not a big deal for a person that dealt with composer.lock before. 
https://github.com/owncloud/gallery/pull/738 passes the CI but has a conflicting lock file.

**Comment by tomneedham** [comment]
solved in #760

**Pull request closed without merging**
