### PR TITLE
[stable9] Do not allow access to write-only shares

### PR DESCRIPTION
**Pull request by LukasReschke**
Backport of https://github.com/owncloud/gallery/pull/665

### CODE REVIEW

**Comment by oparoz** [comment]
1 test is failing, returning a 503 instead of 400.

**Comment by LukasReschke** [comment]
@oparoz Test has been adjusted :)

**Comment by oparoz** [comment]
@LukasReschke - Have you tested it by going to the URL? Are you really shown the Gallery error page with the message "Share is a write-only share (503)" ?
Looking at the code I would expect to receive a 403, as defined here: https://github.com/owncloud/gallery/blob/cacb75dfc988a0bd78fb6643b3011646369eabbc/middleware/envcheckmiddleware.php#L134

**Comment by LukasReschke** [comment]
@oparoz Fixed that issue. Mind having a second look? Thanks a lot :)

**Comment by oparoz** [comment]
@LukasReschke I'm much happier with that version :D 
:+1:

**Comment by LukasReschke** [comment]
Yay :-)

**Pull request merged**
