### PR TITLE
nice emptycontent message look, fix #290

### LINKED ISSUE #290: Update the "no pictures found" landing page to be in line with Files
The default design includes a large icon and a friendly text and we should imitate that.

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix https://github.com/owncloud/gallery/issues/290, please review @oparoz @deMattin @setnes @owncloud/designers 

capture du 2015-09-23 22-53-51

### CODE REVIEW

**Comment by karlitschek** [comment]
very nice! :+1:

**Comment by oparoz** [comment]
Thanks for fixing this :) 
I'll test it asap to confirm it works as advertised.

**Comment by raghunayyar** [comment]
Looks good. Getting this in .:+1:

**Comment by oparoz** [comment]
@jancborchardt - Reopening as public page looks broken, with footer above the message. I really need to start publishing acceptance tests...

broken_public

**Comment by oparoz** [comment]
@MorrisJobke - It's broken.

**Comment by MorrisJobke** [comment]
> @MorrisJobke - It's broken.

Why blame me? I only deleted the branch ;)

**Comment by oparoz** [comment]
@MorrisJobke - I'm not blaming you, I was just saying, don't delete the branch as I've re-opened it because of a problem :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke - I'm not blaming you, I was just saying, don't delete the branch as I've re-opened it because of a problem :)

But this is a branch that is the same as master. You need to revert it. ;)

**Comment by oparoz** [comment]
Yeah, it's true that even if he adds to the branch it will be a new PR... So let's delete it here and create a new issue... Thanks!

**Comment by oparoz** [comment]
I also just found that it's actually also unrelated to this patch...

**Pull request merged**
