### PR TITLE
Fix gallery upload

### PR DESCRIPTION
**Pull request by jvillafanez**
Fixes: https://github.com/owncloud/gallery/issues/740

Licence: MIT or AGPL

### Features

* ...
* ...

### Caveats

* ...
* ...

### Tested on
Firefox, ownCloud 10.0.7
- [ ] Windows/Firefox
- [ ] Android 6.1/Chrome

### TODO

- [ ] ...
- [ ] ...

### Check list

- [ ] Code is properly documented
- [ ] Code is properly formatted
- [ ] Commits have been squashed
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1: looks fine but it was stated in the ticket that this is only part of the fix. So let's merge this first.

**Comment by mmattel** [comment]
@ownclouders rebase

**Comment by phil-davis** [comment]
@mmattel ownclouders seem to be asleep here. I  did a local rebase and force push.

**Comment by mmattel** [comment]
Thanks @phil-davis 
travis errored again and complained about some npm stuff.
Can you take a look on it why it failed (and how to make it pass) ?

**Comment by phil-davis** [comment]
I guess someone restarted a Travis job - all green now.

**Comment by mmattel** [comment]
@PVince81 everything green now - merging as you intended above?

**Comment by phil-davis** [comment]
I quickly tried uploading a png file over the top of a existing png file, using core stable10 and this gallery branch. A popup comes saying "Error loading file exists template".

So something is amiss here. I don't have priority right now to play more...

**Comment by PVince81** [comment]
this is only part of a fix, not fully working yet. a step forward until we find time to fix it fully

**Comment by jvillafanez** [comment]
Known problems with the fix are described in https://github.com/owncloud/gallery/issues/740#issuecomment-378197847
We need to schedule more time to fully fix the problem.

**Pull request merged**
