### PR TITLE
- added Content Security for OC 8.1

### PR DESCRIPTION
**Pull request by Spacefish**

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks for taking care of that. I'll test it as soon as I've installed ownCloud master somewhere.

Also, are you licensing this under the AGPL or MIT license?

**Comment by Spacefish** [comment]
ok :) sounds great.
Regarding the license, i would say MIT if this is ok, i guess it allows
broader use. If you prefer AGPL this would be ok too!
Please choose yourself, i don´t really care :D

Best regards,
Timo

2015-03-15 13:26 GMT+01:00 Olivier Paroz notifications@github.com:

**Comment by oparoz** [comment]
Well, I can't chose for you, but I think MIT is easier to work with without having to sign anything.

**Comment by Spacefish** [comment]
Ok i herby choose MIT! :)
b.t.w. i signed the owncloud contributors agreement ~20 min ago (if this
helps).
Thanks!

2015-03-15 15:24 GMT+01:00 Olivier Paroz notifications@github.com:

**Comment by oparoz** [comment]
Ah, that's great :). I've noticed that they don't require the signed agreement for apps, but I'd rather be safe than sorry :)
Will keep you posted on this PR.

**Comment by oparoz** [comment]
This has now been merged via #109.
Thank you for your contribution!

**Pull request closed without merging**
