### PR TITLE
float file/gallery view toggle to the right so it doesn't conflict with the New/Upload function

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @oparoz @deMattin @owncloud/designers @nickvergessen @schiesbn thanks! :)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by MTRichards** [comment]
Thanks Tobi!

**Comment by jancborchardt** [comment]
@MTRichards I guess wrong issue? ;)

**Comment by tomneedham** [comment]
:+1:

**Comment by oparoz** [comment]
OK, so now, fix it in this PR so that we can finally merge it:
https://github.com/owncloud/gallery/pull/148

**Pull request merged**
