### PR TITLE
Only show sort buttons if there is more than 1 image in the album.

### PR DESCRIPTION
**Pull request by virajparimi**
Fixes: #573 

Licence: AGPL
### Description

Fixes the problem and shows sort button if more than 1 image in album.
### Features

Works for images as well as folders.
### Tested on
- [X] Ubuntu 14.04/Chrome
### Reviewers

@oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
> Fixes the problem and shows sort button if more than 1 image in album.

It would be good if you could describe in more details the logic you've used. That way the principles can be validated before the code.

Looking at the code, I see a couple of issues:
1. The first conditions shows the buttons if there are 0 albums or images
2. The 2nd conditions allows for 2 elements to be shown on screen

So it seems you need to write more tests in your test plan to try and cover more cases

**Comment by virajparimi** [comment]
@oparoz First condition is pretty trivial to fix. But the second condition is for when 1 folder and 1 image is present. At that time should we show sort buttons or not?

**Comment by oparoz** [comment]
> when 1 folder and 1 image is present. At that time should we show sort buttons or not?

Yes. Even though it appears that no sorting would be necessary, because all elements can bee seen at once, I have no way of defining from which point it is.
Should people not have the capability to sort less than 5 elements? 3? 10? I don't think we can arbitrarily pick one.

**Comment by oparoz** [comment]
Ah and I read the 2nd condition wrong. So, the logic is correct there, but try to combine 1 & 2 if you can.

If we have more than one element -> show buttons

**Comment by virajparimi** [comment]
@oparoz Have a look at this one.

**Comment by oparoz** [comment]
That doesn't work if I have 10 images and 0 albums, no? (Add this case to the test plan if it doesn't)

**Comment by virajparimi** [comment]
@oparoz My bad, I missed those conditions. Anyways the new one adds those conditions as well.

**Comment by oparoz** [comment]
OK, now try to combine these conditions into 1, if possible.

**Comment by virajparimi** [comment]
@oparoz Have done. Please check. Thanks!

**Comment by oparoz** [comment]
I think I have a better idea. Add the number of images and albums and if the sum is greater than one, then show the buttons. What do you think?

**Comment by virajparimi** [comment]
@oparoz :+1: Certainly a good idea, as it decreases the number of redundant comparisions and combines them. Have updated the file.

**Comment by oparoz** [comment]
OK about the idea, but have you tested your code? By looking at it, I'd say the way you wrote it doesn't work.

**Comment by virajparimi** [comment]
@oparoz Sorry for the inconvenience.

**Comment by oparoz** [comment]
We all make mistakes :), but that's why I think the test plan is important. It makes it easy to quickly review all cases.

Let me know when you've tested the solution and I'll review it.

**Comment by virajparimi** [comment]
@oparoz I have tested it and as far as I can see there are no errors. I worked with 1 image, then 2 images, similarly for albums and then both of the together.

**Comment by oparoz** [comment]
OK, I'll let you summon some testers ;)

**Comment by virajparimi** [comment]
Ok, @imjalpreet @tahaalibra  Need your reviews about this. What do you think?

**Comment by tahaalibra** [comment]
i think @mbtamuli was working on this. please review...
i will test this and comeback to you

**Comment by mbtamuli** [comment]
Everything is working properly. :+1: 
- 1 Image.
- 1 Folder.
- 1 Image + 1 Folder
- Multiple Images
- Multiple Folders
- Multiple Images + Multiple Folders

**Comment by oparoz** [comment]
Thanks @mbtamuli

**Pull request merged**
