### PR TITLE
Use .text instead of .html

### PR DESCRIPTION
**Pull request by LukasReschke**
@oparoz You might want to backport this to the appstore releases…

### CODE REVIEW

**Comment by oparoz** [comment]
I'll update it, but is it just a good practice thing or is there a real risk here? I don't see how the filename can be used against the user in this case.

**Comment by LukasReschke** [comment]
> I'll update it, but is it just a good practice thing or is there a real risk here? 

Just upload a file `<script>alert(1)<script>` and access the Gallery app and check the HTML. This leads to XSS.

It's not directly executed in this case since we use CSP but [for example MS IE does not support CSP](https://caniuse.com/#feat=contentsecuritypolicy).

**Comment by LukasReschke** [comment]
See https://www.owasp.org/index.php/Cross-site_Scripting_(XSS) for some more explanation.

**Comment by oparoz** [comment]
Yes, but I didn't think it was possible to create such a file. Linux just let me, so there is a real risk :|

**Comment by LukasReschke** [comment]
> Yes, but I didn't think it was possible to create such a file. Linux just let me, so there is a real risk :|

Well just do via the web interface ;)

**Comment by oparoz** [comment]
> Well just do via the web interface ;)

:-O  that worked... but that's a problem because those files won't sync.

**Pull request merged**
