### PR TITLE
create specific folder icon for Gallery, fix #433

### LINKED ISSUE #433: Create gallery album icon for when we can't show images
When we can't fetch at least one thumbnail to put in the album representation, we get a folder icon, but I'd like to have a proper album icon, based on something like this

---

@jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Fix #433 by adding a specific Gallery-folder-icon. Please review @oparoz @owncloud/designers

### CODE REVIEW

**Comment by oparoz** [comment]
Maybe put it in core so that people can theme it like the rest of the icons? At some point, you could have albums for music, documents etc and people could pick the folder they want to use in the Files app in case it requires too much power to detect automatically.

**Comment by mmattel** [comment]
:+1:

**Comment by oparoz** [comment]
@jancborchardt What do you think about having all sorts of multimedia folder icons in core for easy theming?

**Comment by jancborchardt** [comment]
@oparoz I’d say we should first get this simple change in and improve later. :) For now it’s just a file type icon change.

**Pull request merged**
