### PR TITLE
Added Delete Button in Slideshow

### PR DESCRIPTION
**Pull request by oparoz**
Local duplicate of #658 and rebased.

Fixes: #649
- [x] Disable on read-only shares
- [x] Disable on images which can be deleted
- [x] Fix icon
- [x] Fix current image index for case where image is the last one
- [x] Fix delete from Files
- [ ] Fix wrong method for webdav endpoint

### CODE REVIEW

**Comment by oparoz** [comment]
There is a bug when going in reverse direction.

**Comment by manishbisht** [comment]
Bug Resolved @oparoz :)

**Comment by oparoz** [comment]
Thanks, I'm guessing you removed that extra delete statement.

You can find my fix and cleanup here:
https://github.com/interfasys/galleryplus/pull/47/commits/96dffb72d895e30a6d3bf52ee31c232ff4b0db52

**Comment by manishbisht** [comment]
Yes, I have only removed the extra delete statement @oparoz  :)

**Comment by oparoz** [comment]
OK, I've pushed my cleanup as there were other issues.
There is still one problem left if you want to take a look at it: The icon should not be shown on shared albums unless the share is read-write.

**Comment by manishbisht** [comment]
Ok. I will look into this after my exams. Can we close the original issue #649 @oparoz

**Comment by oparoz** [comment]
Done

**Comment by oparoz** [comment]
Actually, we can't close the issue as it isn't merged.

**Comment by manishbisht** [comment]
Can we merge this PR with owncloud gallery ?

**Comment by oparoz** [comment]
Not before there is a stable branch to merge to.

**Comment by oparoz** [comment]
And before the bugs are solved, of course.

**Comment by manishbisht** [comment]
Ok. Actually I want to claim the bounty for this issue :p

**Comment by oparoz** [comment]
> Actually I want to claim the bounty for this issue :p

Then you need to fix the bugs.

**Comment by manishbisht** [comment]
Ok. I will try to fix this bug @oparoz :)

**Comment by oparoz** [comment]
OK, don't forget to pull the changes and then to create a new commit containing ONLY your changes.

**Comment by manishbisht** [comment]
I think the process to check the share properties during files deletion must be present in the files app also.

**Comment by oparoz** [comment]
I assume so since a read-write share can be fully managed from the Files side. 
That's the `files_sharing` app btw.

**Comment by oparoz** [comment]
And there is another issue. The delete icon used doesn't have any shadows and thus make it invisible on a light background.

hidden_delete_icon

**Comment by oparoz** [comment]
OK, so now the only thing missing is the icon.

**Comment by manishbisht** [comment]
@oparoz I have shared one album and opened it in browser. It is showing me Gallery.token is undefined and when I opened the same image in slideshow it shows Gallery.token.is undefined

**Comment by manishbisht** [comment]
Its working with latest commit :+1:

**Comment by oparoz** [comment]
2 more problems:
- ~~Fix delete from Files~~
- Fix wrong method for webdav endpoint

**Pull request merged**
