### PR TITLE
Only load for apps/files and apps/files_sharing

### PR DESCRIPTION
**Pull request by rullzer**
Second try for https://github.com/owncloud/gallery/issues/619

@PVince81 @oparoz please have a look.

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: looks good

**Comment by oparoz** [comment]
Test plan is missing, so reviewers, make sure you test this case: https://github.com/owncloud/gallery/issues/619#issuecomment-201832515

**Comment by SergioBertolinSG** [comment]
:+1: works (also https://github.com/owncloud/gallery/pull/635#issuecomment-203368357)

**Comment by oparoz** [comment]
Thank you! I'll check later today.

**Comment by PVince81** [comment]
I'll leave it up to you to merge it @oparoz (and the backport), hopefully before the end of the week so we can have it in the next RC.

**Comment by oparoz** [comment]
I will, thank @PVince81

**Pull request merged**
