### PR TITLE
Bouncy scroll for iOS devices

### PR DESCRIPTION
**Pull request by ghost**
Scroll more smothly for webkit browser(mobile)

### CODE REVIEW

**Comment by oparoz** [comment]
Thank you for your contribution. @jancborchardt will take a look at it :)

**Comment by ghost** [comment]
This change just works for iOS Safari and iOS chrome

**Comment by jancborchardt** [comment]
:+1: another review please @owncloud/designers and anyone who has an iOS device @LukasReschke @karlitschek

**Comment by karlitschek** [comment]
looks good :+1:

**Comment by jancborchardt** [comment]
@fuhaoshih you need to rebase your branch. :) Simply:

```
git pull origin master
git checkout patch-2
git rebase master
git push -f origin patch-2
```

Or just make a new pull request with that line change. Then we directly pull it in. :)

**Comment by mmattel** [comment]
@fuhaoshih, a rebase like suggested from @jancborchardt would be great so the PR can get pulled.

**Comment by jancborchardt** [comment]
@oparoz or maybe you can cherry-pick this and do a new pull request so we can get this in?

**Comment by jancborchardt** [comment]
Superseded by https://github.com/owncloud/gallery/pull/368 because we need to get this in. :)

**Pull request closed without merging**
