### PR TITLE
Adds the form which allows a user to add the shared files to their ownCloud

### PR DESCRIPTION
**Pull request by oparoz**
Solution for #144

### CODE REVIEW

**Comment by oparoz** [comment]
@jancborchardt @libasys @nclm 

I've only tested this on OC8 so far.

**Comment by oparoz** [comment]
Also @deMattin

**Comment by jancborchardt** [comment]
cc @PVince81 @schiesbn for the server-to-server sharing review

**Comment by oparoz** [comment]
So, any problem with the approach @PVince81 @schiesbn ?

Is it working for you @demattin @libasys @setnes @nclm

**Comment by schiessle** [comment]
I tried the server-to-server share part... Works :+1:

**Comment by oparoz** [comment]
Thank you!

**Comment by jancborchardt** [comment]
@oparoz please merge https://github.com/owncloud/galleryplus/pull/139, otherwise I can’t test. ;)

**Comment by oparoz** [comment]
I can't merge that PR. Branches have to be renamed if the way forward is to mirror the core setup.

If you're stuck on 8.1 though, you can use the ultimatedev branch which contains all the latest PRs.

**Comment by jancborchardt** [comment]
@oparoz ok, it doesn’t have to necessarily be merging that branch. The point is that `max-version="8.0.99"` is not a proper attribute, and it should be `max-version="8.1"` ;)

**Comment by oparoz** [comment]
Ah, no, this is to say that it can be installed on all 8.0.x version, but not 8.1.x, assuming development versions of 8.1 are never named something like 8.0.9.1

**Comment by jancborchardt** [comment]
@oparoz delete merged branches please ;) press the »Delete branch« button here.

**Pull request merged**
