### PR TITLE
Delay navigation route loading

### PR DESCRIPTION
**Pull request by oparoz**
- [x] Fix for #293

### CODE REVIEW

**Comment by oparoz** [comment]
So, the first patch is for you, @Xenopathic . Thanks for fixing the OCS routes and letting me know about the delayed routes.

**Comment by oparoz** [comment]
All tests pass except the ones which require the return of the deleted icons in core.

**Comment by RobinMcCorkell** [comment]
:+1: (if my +1 means anything in this repo that is :smile:)

**Comment by oparoz** [comment]
Yeah, that's the thing. Almost no-one is familiar with the code, so there is little point in waiting for a +1 when I make little changes, but since this is AppFramework code, it should be understandable by other devs.

Thanks for the review :)

**Comment by oparoz** [comment]
@Xenopathic - Now this is untestable... 

`$navigationManager->getAll()`

>  [Symfony\Component\Routing\Exception\RouteNotFoundException] Unable to generate a URL for the named route "gallery.page.index" as such route does not exist.

**Comment by RobinMcCorkell** [comment]
That can only happen if the app routes are not being loaded. It's unrelated to this change...

**Comment by oparoz** [comment]
The app routes are never loaded if you're not logged in if I'm not mistaken, so I guess I just didn't see it before because the app.php file is just a bunch of method calls, so PHPUnit was reporting all of these as covered.

**Pull request merged**
