### PR TITLE
Don't forget to show the [+] button when activating the controls button

### PR DESCRIPTION
**Pull request by oparoz**
Fixes: #631
### Tests

See #631 
### Reviewers

@manishbisht @tahaalibra @viraj96 @imjalpreet @mbtamuli @rahulgoyal030 @shubhrajodiya @harshjv @kartik69 @senorsen

### CODE REVIEW

**Comment by oparoz** [comment]
@eknoes if you want to test this fix. It's obvious to see the problem when using your new feature :)

**Comment by virajparimi** [comment]
Yes, this works. Tested on Ubuntu 14.04/Chrome.

**Comment by manishbisht** [comment]
It's working checked on Ubuntu 14.04/Chrome and Ubuntu 14.04/Firefox.

**Comment by oparoz** [comment]
Thank you guys

**Pull request merged**
