### PR TITLE
[stable9] Fix unauthenticated route in files_drop app

### PR DESCRIPTION
**Pull request by PVince81**
Backport of https://github.com/owncloud/gallery/pull/620 to stable9

@rullzer @oparoz

### CODE REVIEW

**Comment by rullzer** [comment]
Mmmm apparently travis is unhappy. @oparoz could you have a look?

**Comment by oparoz** [comment]
I've restarted those instances. It's usually nothing to worry about (just annoying). Some glitches in the acceptance tests on stable9 or Travis being slow.

**Comment by rullzer** [comment]
Thanks :)

**Comment by PVince81** [comment]
Travis tests passed, merge ? @oparoz @rullzer

**Comment by oparoz** [comment]
@PVince81 Unfortunately, no. I had to revert the original PR because of a regression.

**Pull request closed without merging**
