### PR TITLE
fix order of Gallery app in app navigation

### PR DESCRIPTION
**Pull request by jancborchardt**
The idea is to have the sorting start with: Files, Activity, Gallery etc.

Please review @owncloud/designers @oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Tested and works :+1:

**Comment by oparoz** [comment]
@jancborchardt - I'm OK with a backport to stable9 if you want it there as well.

**Comment by jancborchardt** [comment]
Yeah, good call. Backport at https://github.com/owncloud/gallery/pull/640

**Pull request merged**
