### PR TITLE
increase filename visibility, same as for icons in slideshow

### PR DESCRIPTION
**Pull request by jancborchardt**
Similar to the icon visibility fix in core https://github.com/owncloud/core/pull/19380, this also makes the filename visible on bright background.

Please review @owncloud/designers @oparoz @deMattin @setnes

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by oparoz** [comment]
I'd say: almost

If I compare the filename with the icons, it seems the border is missing, which makes it difficult to read on white.

no_border

**Comment by jancborchardt** [comment]
@oparoz there’s no such thing as text-border unfortunately. I’d say it’s better than nothing and we should merge. (Hello from vacation btw, this is an exception cc @owncloud/designers you need to handle this the next 2 weeks. ;)

**Comment by stefan-niedermann** [comment]
> there’s no such thing as text-border unfortunately

Nope, but you can use text-shadow to simulate a text-border.

``` css
    text-shadow:  1px  1px 1px black,
         1px -1px 1px black,
        -1px  1px 1px black,
        -1px -1px 1px black;
```

**Comment by oparoz** [comment]
Thanks for the tip @stefan-niedermann .

@deMattin @setnes @karlitschek  Please test the updated PR. I think the title now looks similar to the icons :)

@jancborchardt Enjoy the time off :)

**Comment by icewind1991** [comment]
Looks good :+1:

**Pull request merged**
