### PR TITLE
Fix of issue #23066

### PR DESCRIPTION
**Pull request by TDannhauer**
Fixes Bug owncloud/core#23066

### CODE REVIEW

**Comment by oparoz** [comment]
Thanks for the patch @TDannhauer

**Comment by TDannhauer** [comment]
My contribution is MIT licensed

**Comment by nickvergessen** [comment]
:+1:

**Comment by butonic** [comment]
👍 ran into this on stable9, will submit PR

**Comment by butonic** [comment]
@oparoz @DeepDiver1975 CI is broken ...

**Comment by DeepDiver1975** [comment]
> @oparoz @DeepDiver1975 CI is broken ...

a rebase might help - branch has anyhow conflicts which need to be resolved

**Comment by DeepDiver1975** [comment]
okay - the target repo no longer exists - I suggest to recreate this PR

**Comment by PVince81** [comment]
Resent as https://github.com/owncloud/gallery/pull/689

**Pull request closed without merging**
