### PR TITLE
Update info.xml

### PR DESCRIPTION
**Pull request by SergioBertolinSG**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Why did you set the min-version to 9.2?

**Comment by SergioBertolinSG** [comment]
To be consistent with the rest of apps.

**Comment by ChristophWurst** [comment]
> To be consistent with the rest of apps.

I don't get it. Before the app targeted two major releases (9.0 and 9.1) and now it's only 9.2. Is there any reasoning for that?

**Comment by ChristophWurst** [comment]
Is it because the app is shipped?

**Comment by DeepDiver1975** [comment]
> Is it because the app is shipped?

basically yes - a shipped app is only used for that specific major version.

**Pull request merged**
